### ISSUE TITLE
Faltou uma validaçãozinha!

### ISSUE THREAD

**Issue by edysegura** [RodrigoFranco91/DM122-PWA-Trabalho-de-Conclusao-Edy#1]
![image](https://user-images.githubusercontent.com/5324414/97246197-86191700-17db-11eb-9f9e-e057246eea75.png)

**Comment by RodrigoFranco91** [comment]
Bom dia Edy;

Atualizei os input's de Nome e Telefone, agora ambos são Required.

Abç.
